export type ValidSkills =
  | "Next.js"
  | "React"
  | "GraphQL"
  | "Nest.js"
  | "express.js"
  | "Node.js"
  | "MongoDB"
  | "Typescript"
  | "Cloudinary"
  | "Javascript"
  | "HTML 5"
  | "CSS 3"
  | "React Native"
  | "Angular"
  | "Redux"
  | "Judge0 API"
  | "Expo"
  | "Socket.io"
  | "UI/UX Design"
  | "Material UI"
  | "Tailwind CSS"
  | "AWS"
  | "Bootstrap"
  | "Google Auth"
  | "MySQL"
  | "Java"
  | "Databricks"
  | "Python"
  | "Docker"
  | "Kubernetes"
  | "PostgreSQL"
  | "Redis"
  | "Git"
  | "CI/CD"
  | "Jenkins"
  | "FastAPI"
  | "Django"
  | "Vue.js"
  | "Sass"
  | "Firebase"
  | "Azure"
  | "Google Cloud"
  | "Figma"
  | "Webpack"
  | "Jest"
  | "Cypress"
  | "Storybook"
  | "Prisma"
  | "Supabase"
  | "Vercel"
  | "Netlify"
  | "Three.js"
  | "WebGL"
  | "TensorFlow"
  | "PyTorch"
  | "Spring Boot"
  | "Laravel"
  | "PHP"
  | "Flutter"
  | "Dart"
  | "Flask"
  | "Django"
  | "FastAPI"
  | "SQL"
  | "NoSQL"
  | "Monaco Editor"
  |  "API Integration"
  | "Pandas"
  |"React Three Fiber"
  | "React Three Drei"
  | "Matplotlib"
  | "Framer Motion"
  | "TMDB API";

export type ValidCategory =
  | "Full Stack"
  | "Frontend"
  | "Training platform"
  | "Compliance Check"
  | "Backend"
  | "ONDC"
  | "UI/UX"
  | "Web App"
  | "SaaS"
  | "Entertainment"
  | "Coding Tools"
  | "ML"
  | "Portfolio"
  | "3D Design"
  | "Data Science"
  | "Deep Learning"
  | "Web Dev"
  | "Mobile Dev"
  | "Productivity"
  | "3D Modeling";

export type ValidExpType = "Personal" | "Professional";

export type ValidPages =
  | "home"
  | "skills"
  | "projects"
  | "experience"
  | "contact"
  | "contributions"
  | "resume";
